/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Plantas.ManejadorPlanta;
import Vivo.planta;

/**
 *
 * @author byron
 */
public class OpcionesTierra extends javax.swing.JFrame {

      private planta planta;
      
      public OpcionesTierra() {
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
       * code. The content of this method is always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            regresar = new javax.swing.JButton();
            Sembrar = new javax.swing.JButton();
            fondotierra = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setAlwaysOnTop(true);
            setUndecorated(true);
            setResizable(false);
            setType(java.awt.Window.Type.UTILITY);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel1.setText("jLabel1");
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 30));

            regresar.setText("Regresar");
            regresar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        regresarActionPerformed(evt);
                  }
            });
            getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 212, -1, -1));

            Sembrar.setText("Sembrar");
            Sembrar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SembrarActionPerformed(evt);
                  }
            });
            getContentPane().add(Sembrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 174, 83, -1));

            fondotierra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galloSembradorFondo.jpg"))); // NOI18N
            getContentPane().add(fondotierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 250));

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
            setVisible(false);
      }//GEN-LAST:event_regresarActionPerformed

      private void SembrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SembrarActionPerformed
           planta = new planta("planta", 100, "planta1");
            ManejadorPlanta manejadorPlanta = new ManejadorPlanta(planta);
            manejadorPlanta.VidaJugador(jLabel1);
      }//GEN-LAST:event_SembrarActionPerformed


      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton Sembrar;
      private javax.swing.JLabel fondotierra;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JButton regresar;
      // End of variables declaration//GEN-END:variables
}
