/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Terrenos.SuperficieTerreno;

/**
 *
 * @author byron
 */
public class OpcionesAgua extends javax.swing.JFrame {

     private SuperficieTerreno botonPulsado;
     
      public OpcionesAgua(SuperficieTerreno celdaRecibida) {
            initComponents();
            this.botonPulsado = celdaRecibida;

      }

      /**
       * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
       * code. The content of this method is always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            regresar = new javax.swing.JButton();
            Pescar = new javax.swing.JButton();
            fondoPescador = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setAlwaysOnTop(true);
            setUndecorated(true);
            setResizable(false);
            setType(java.awt.Window.Type.UTILITY);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            regresar.setText("Regresar");
            regresar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        regresarActionPerformed(evt);
                  }
            });
            getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 212, -1, -1));

            Pescar.setText("Pescar");
            getContentPane().add(Pescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 174, 83, -1));

            fondoPescador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galloPescadorFondo.jpg"))); // NOI18N
            getContentPane().add(fondoPescador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 250));

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
            setVisible(false);
      }//GEN-LAST:event_regresarActionPerformed


      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton Pescar;
      private javax.swing.JLabel fondoPescador;
      private javax.swing.JButton regresar;
      // End of variables declaration//GEN-END:variables
}
